commit 5

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,43 +11,44 @@ jobs:
   runs-on: ubuntu-latest
   steps:
    - name : "check out code"
-     uses: actions/checkout@v3
+     #uses: actions/checkout@v3
+     run: echo "###########################"
      
-   - name: "install node js 22"
-     uses: actions/setup-node@v3
-     with:
-      node-version: '22'
-     
-   - name: "Node dependency Install"
-     run: npm install
-     
-   - name: "Run test & store log"
-     run: |
-      mkdir -p test-results
-      npm check > test-results/results.txt || echo "Test failed"
-      
-   - name: "Upload test result in artifact"
-     uses: actions/upload-artifact@v3
-     with:
-      name: test-results
-      path: test-results/results.txt
-                  
-   - name: "show result"
-     run: cat test-results
-     
- deploy_job:
-  name: "job_2: deploy_job"
-  runs-on: ubuntu-latest
-  needs: test_job
-  steps:
-   - name : "check out code"
-     uses: actions/checkout@v3
-     
-   - name: "Download artifact"
-     uses: actions/upload-artifact@v3
-     with:
-      name: test-results
-      path: test-results/results.txt
+#   - name: "install node js 22"
+#     uses: actions/setup-node@v3
+#     with:
+#      node-version: '22'
+#     
+#   - name: "Node dependency Install"
+#     run: npm install
+#     
+#   - name: "Run test & store log"
+#     run: |
+#      mkdir -p test-results
+#      npm check > test-results/results.txt || echo "Test failed"
+#      
+#   - name: "Upload test result in artifact"
+#     uses: actions/upload-artifact@v3
+#     with:
+#      name: test-results
+#      path: test-results/results.txt
+#                  
+#   - name: "show result"
+#     run: cat test-results
+#     
+# deploy_job:
+#  name: "job_2: deploy_job"
+#  runs-on: ubuntu-latest
+#  needs: test_job
+#  steps:
+#   - name : "check out code"
+#     uses: actions/checkout@v3
+#     
+#   - name: "Download artifact"
+#     uses: actions/upload-artifact@v3
+#     with:
+#      name: test-results
+#      path: test-results/results.txt
 
 
 
